/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch design tokens — Neo-Browser
        bg: '#F8FAFC',
        background: '#f7faf8',
        surface: '#FFFFFF',
        'surface-dim': '#d7dbd9',
        'surface-bright': '#f7faf8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f3',
        'surface-container': '#ebefed',
        'surface-container-high': '#e5e9e7',
        'surface-container-highest': '#e0e3e1',
        'surface-variant': '#e0e3e1',
        'surface-tint': '#006a63',
        'on-surface': '#181c1c',
        'on-surface-variant': '#3e4947',
        'on-background': '#181c1c',
        'inverse-surface': '#2d3130',
        'inverse-on-surface': '#eef1f0',
        outline: '#6e7977',
        'outline-variant': '#bdc9c6',
        primary: '#005c55',
        'primary-hover': '#115E59',
        'primary-container': '#0f766e',
        'on-primary': '#ffffff',
        'on-primary-container': '#a3faef',
        'inverse-primary': '#80d5cb',
        'primary-fixed': '#9cf2e8',
        'primary-fixed-dim': '#80d5cb',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#00504a',
        secondary: '#5a5f62',
        'secondary-container': '#dce0e4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5e6367',
        'secondary-fixed': '#dfe3e7',
        'secondary-fixed-dim': '#c3c7cb',
        'on-secondary-fixed': '#171c1f',
        'on-secondary-fixed-variant': '#43474b',
        tertiary: '#7f4025',
        'tertiary-container': '#9c573a',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffe5db',
        'tertiary-fixed': '#ffdbce',
        'tertiary-fixed-dim': '#ffb598',
        'on-tertiary-fixed': '#370e00',
        'on-tertiary-fixed-variant': '#72361b',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        border: '#E2E8F0',
        text: '#0F172A',
        'text-muted': '#475569',
        success: '#15803D',
        'warning-bg': '#FFFBEB',
        'warning-border': '#FDE68A',
        'warning-text': '#854D0E',
        focus: '#2563EB',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '32px',
        'section-padding-mobile': '48px',
        'section-padding-desktop': '72px',
        'max-width': '1160px',
        gutter: '24px',
      },
      maxWidth: {
        content: '1160px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display': ['52px', { lineHeight: '1.1', fontWeight: '700' }],
        'display-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
        'title-lg': ['20px', { lineHeight: '1.5', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '1.5', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-xs': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
