/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Spider-Man Marvel Design Tokens
        bg: '#080C14',
        background: '#080C14',
        surface: '#0F172A',
        'surface-dim': '#0B1120',
        'surface-bright': '#1E293B',
        'surface-container-lowest': '#0A0E17',
        'surface-container-low': '#0F172A',
        'surface-container': '#1E293B',
        'surface-container-high': '#334155',
        'surface-container-highest': '#475569',
        'surface-variant': '#1E293B',
        'surface-tint': '#E62429',
        'on-surface': '#F8FAFC',
        'on-surface-variant': '#CBD5E1',
        'on-background': '#F8FAFC',
        'inverse-surface': '#F8FAFC',
        'inverse-on-surface': '#0F172A',
        outline: '#E62429',
        'outline-variant': 'rgba(230, 36, 41, 0.3)',
        primary: '#E62429', // Spider-Man Crimson
        'primary-hover': '#FF2E35',
        'primary-container': '#990006',
        'on-primary': '#ffffff',
        'on-primary-container': '#FFD1D3',
        'inverse-primary': '#FF7075',
        'spider-blue': '#0047BB', // Spider-Man Suit Blue
        'spider-blue-hover': '#005CE6',
        'spider-gold': '#FFD700', // Iron-Spider Gold
        secondary: '#94A3B8',
        'secondary-container': '#1E293B',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#E2E8F0',
        tertiary: '#0047BB',
        'tertiary-container': '#1E3A8A',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#DBEAFE',
        error: '#EF4444',
        'error-container': '#7F1D1D',
        'on-error': '#ffffff',
        'on-error-container': '#FEE2E2',
        border: 'rgba(230, 36, 41, 0.25)',
        text: '#F8FAFC',
        'text-muted': '#94A3B8',
        success: '#10B981',
        'warning-bg': '#1E1B13',
        'warning-border': '#B45309',
        'warning-text': '#FBBF24',
        focus: '#E62429',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '32px',
        'section-padding-mobile': '48px',
        'section-padding-desktop': '72px',
        'max-width': '1160px',
        gutter: '24px',
      },
      maxWidth: {
        content: '1160px',
      },
      fontFamily: {
        sans: ['Outfit', 'Inter', 'system-ui', 'sans-serif'],
        display: ['Orbitron', 'Outfit', 'sans-serif'],
      },
      fontSize: {
        'display': ['52px', { lineHeight: '1.1', fontWeight: '800' }],
        'display-mobile': ['32px', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
        'title-lg': ['20px', { lineHeight: '1.5', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '1.5', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-xs': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      boxShadow: {
        'spider-glow': '0 0 25px rgba(230, 36, 41, 0.4)',
        'spider-glow-lg': '0 0 40px rgba(230, 36, 41, 0.6)',
        'spider-blue-glow': '0 0 25px rgba(0, 71, 187, 0.5)',
      },
    },
  },
  plugins: [],
}
